	.nlist
*
* doscall.mac X68k XC Compiler v2.11 Copyright 1990,93 SHARP/Hudson
*
DOS	macro	callname
	dc.w	callname
	endm
*
* 注意
* Version 3.00以後のX68030対策として、$FF50から$FF7Fのファンクションは、$FF
* 80から$FFAFに移動しています。__mainの処理のなかで、Version 3.00以前のDOS
* の場合は、ファンクションテーブルの書き替えを行っていますので、Cで使用する
* 場合以外でこのDOSCALL.MACを使用する場合は、必ず新設のDOSINIT()関数を呼び
* 出してから使用する様に気をつけてください。
* RESERVED になっているファンクションコールの処理を変更したり、呼び出したり
* してはいけません。
* $fff0～$fff2までのファンクション番号は、終了、ＣＴＲＬ＋Ｃ、アボートの
* 処理を_INTVCSによって変更する場合に使用するもので、ファンクションコール
* ではありません。
* また、$fff3～$ffffまでのファンクションコールは、処理を変更できません。
*
_EXIT		equ	$ff00
_GETCHAR	equ	$ff01
_PUTCHAR	equ	$ff02
_COMINP		equ	$ff03
_COMOUT		equ	$ff04
_PRNOUT		equ	$ff05
_INPOUT		equ	$ff06
_INKEY		equ	$ff07
_GETC		equ	$ff08
_PRINT		equ	$ff09
_GETS		equ	$ff0a
_KEYSNS		equ	$ff0b
_KFLUSH		equ	$ff0c
_FFLUSH		equ	$ff0d
_CHGDRV		equ	$ff0e
_CHDRV		equ	$ff0e
_DRVCTRL	equ	$ff0f
_CONSNS		equ	$ff10
_PRNSNS		equ	$ff11
_CINSNS		equ	$ff12
_COUTSNS	equ	$ff13
*RESERVED		$ff14
*RESERVED		$ff15
*RESERVED		$ff16
_FATCHK		equ	$ff17
*RESERVED		$ff18
_CURDRV		equ	$ff19
_GETSS		equ	$ff1a
_FGETC		equ	$ff1b
_FGETS		equ	$ff1c
_FPUTC		equ	$ff1d
_FPUTS		equ	$ff1e
_ALLCLOSE	equ	$ff1f
_SUPER		equ	$ff20
_FNCKEY		equ	$ff21
_KNJCTRL	equ	$ff22
_CONCTRL	equ	$ff23
_KEYCTRL	equ	$ff24
_INTVCS		equ	$ff25
_PSPSET		equ	$ff26
_GETTIM2	equ	$ff27
_SETTIM2	equ	$ff28
_NAMESTS	equ	$ff29
_GETDATE	equ	$ff2a
_SETDATE	equ	$ff2b
_GETTIME	equ	$ff2c
_SETTIME	equ	$ff2d
_VERIFY		equ	$ff2e
_DUP0		equ	$ff2f
_VERNUM		equ	$ff30
_KEEPPR		equ	$ff31
_GETDPB		equ	$ff32
_BREAKCK	equ	$ff33
_DRVXCHG	equ	$ff34
_INTVCG		equ	$ff35
_DSKFRE		equ	$ff36
_NAMECK		equ	$ff37
_MKDIR		equ	$ff39
_RMDIR		equ	$ff3a
_CHDIR		equ	$ff3b
_CREATE		equ	$ff3c
_OPEN		equ	$ff3d
_CLOSE		equ	$ff3e
_READ		equ	$ff3f
_WRITE		equ	$ff40
_DELETE		equ	$ff41
_SEEK		equ	$ff42
_CHMOD		equ	$ff43
_IOCTRL		equ	$ff44
_DUP		equ	$ff45
_DUP2		equ	$ff46
_CURDIR		equ	$ff47
_MALLOC		equ	$ff48
_MFREE		equ	$ff49
_SETBLOCK	equ	$ff4a
_EXEC		equ	$ff4b
_EXIT2		equ	$ff4c
_WAIT		equ	$ff4d
_FILES		equ	$ff4e
_NFILES		equ	$ff4f

_SETPDB		equ	$ff80	*50
_GETPDB		equ	$ff81	*51
_SETENV		equ	$ff82	*52
_GETENV		equ	$ff83	*53
_VERIFYG	equ	$ff84	*54
_COMMON		equ	$ff85	*55
_RENAME		equ	$ff86	*56
_FILEDATE	equ	$ff87	*57
_MALLOC2	equ	$ff88	*58
_MAKETMP	equ	$ff8A	*5a
_NEWFILE	equ	$ff8B	*5b
_LOCK		equ	$ff8C	*5c
*RESERVED		$ff8E	*5e
_ASSIGN		equ	$ff8F	*5f
_FFLUSH_SET	equ	$ffAA	*7a
_OS_PATCH	equ	$ffAB	*7b
_GET_FCB_ADR	equ	$ffAC	*7c
_S_MALLOC	equ	$ffAD	*7d
_S_MFREE	equ	$ffAE	*7e
_S_PROCESS	equ	$ffAF	*7f

_EXITVC		equ	$fff0
_CTRLVC		equ	$fff1
_ERRJVC		equ	$fff2
_DISKRED	equ	$fff3
_DISKWRT	equ	$fff4
_INDOSFLG	equ	$fff5
_SUPER_JSR	equ	$fff6
_BUS_ERR	equ	$fff7
_OPEN_PR	equ	$fff8
_KILL_PR	equ	$fff9
_GET_PR		equ	$fffa
_SUSPEND	equ	$fffb
_SLEEP_PR	equ	$fffc
_SEND_PR	equ	$fffd
_TIME_PR	equ	$fffe
_CHANGE_PR	equ	$ffff
	.list
