name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install wine32
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine32
    - name: Install deps
      run: sudo apt-get install -y portaudio19-dev libportaudio2
    - uses: actions/checkout@v4
      submodules: true
    - name: make
      run: make
